### ISSUE TITLE
Bypass for anti-health indicator 

### ISSUE THREAD

**Issue by IceWaffles** [LaserSlime/AntiHealthIndicator#5]
A bypass on latest Purpur 1.19.2 - correct protocolLib dev version is used (latest possible for 1.19.2) - via version is installed.

This mod https://www.planetminecraft.com/mod/164-better-pvp-v10/ (Better PvP) bypasses it.

**Comment by LaserSlime** [comment]
Cannot reproduce this. I used the same setup except on Purpur 1.19.3, because I couldn't find the download for Purpur 1.19.2. Are you sure the plugin was enabled correctly (check startup logs)? What client version were you using and what other plugins do you use?
Also there is really no such thing as "bypassing" this as this does not detect the health indicator, it just prevents the mod from receiving information about the health.

**Comment by IceWaffles** [comment]
I'm not sure if it's a version problem between 1.19.2 and 1.19.3. And yes, the plugin starts up correctly. I will test without plugins and get back to you

Edit: you can download purpur 1.19.2 here: https://api.purpurmc.org/v2/purpur/1.19.2/latest/download

**Comment by LaserSlime** [comment]
Still can't reproduce on purpur 1.19.2 with 1.19.3 client.

**Comment by IceWaffles** [comment]
It's fine, I've got it sorted. I think it was a broken config of some sort
